plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - verifyReleaseCmd: "make release-verify"
      prepareCmd: "make release-prepare NEXT_VERSION=${nextRelease.version} RELEASE_NOTES='${nextRelease.notes}'"
      publishCmd: "make release-publish NEXT_VERSION=${nextRelease.version}"
      successCmd: "make release-list"
  - - "@semantic-release/github"
    - assets:
        - path: "build/package.zip"
          label: "Package"
        - path: "build/package_repository.zip"
          label: "Package Repository"

branches:
  - '+([0-9])?(.{+([0-9]),x}).x'
  - 'main'
  # TODO: REMOVE ⬇️
  - 'next'
  - 'next-major'
  - { name: 'beta', prerelease: true }
  - { name: 'alpha', prerelease: true }
