name: Build & push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    steps:
    - uses: actions/checkout@v2

    - name: Install Carvel tools
      run: |
        ./.github/workflows/tools/ytt.sh
        ./.github/workflows/tools/kbld.sh
        ./.github/workflows/tools/imgpkg.sh

    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & push
      run: make
